#!/bin/bash

set -e
set -o pipefail

readonly d="$(cd "$(dirname "$0")" || exit 1 ; pwd)"
readonly dest="${d}/../bin/kind"
readonly version="v0.31.0"

log() {
    echo >&2 "$(basename "$0"): $*"
}

install() {
    OS_NAME="$(uname -s)"
    case "${OS_NAME}" in
        "Darwin" | "Linux")
            OS_NAME="$(echo "$OS_NAME" | tr '[:upper:]' '[:lower:]')"
            ;;
        *)
            log "${OS_NAME} is not supported!"
            return 1
            ;;
    esac
    ARCH="$(arch | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/')"
    url="https://kind.sigs.k8s.io/dl/${version}/kind-${OS_NAME}-${ARCH}"
    curl -L -s -o "$dest" "$url"
    chmod +x "$dest"
}

if [[ ! -x "$dest" ]] ; then
    install
fi
"$dest" "$@"
