// Code generated by "goconfig -field Labels labels.Set|CleanupLease bool|LeaderElectTimeout time.Duration|LeaseDuration time.Duration|RenewDeadline time.Duration|RetryPeriod time.Duration -option -output config_generated.go"; DO NOT EDIT.

package lease

import (
	"time"

	"k8s.io/apimachinery/pkg/labels"
)

type ConfigItem[T any] struct {
	modified     bool
	value        T
	defaultValue T
}

func (s *ConfigItem[T]) Set(value T) {
	s.modified = true
	s.value = value
}
func (s *ConfigItem[T]) Get() T {
	if s.modified {
		return s.value
	}
	return s.defaultValue
}
func (s *ConfigItem[T]) Default() T {
	return s.defaultValue
}
func (s *ConfigItem[T]) IsModified() bool {
	return s.modified
}
func NewConfigItem[T any](defaultValue T) *ConfigItem[T] {
	return &ConfigItem[T]{
		defaultValue: defaultValue,
	}
}

type Config struct {
	Labels             *ConfigItem[labels.Set]
	CleanupLease       *ConfigItem[bool]
	LeaderElectTimeout *ConfigItem[time.Duration]
	LeaseDuration      *ConfigItem[time.Duration]
	RenewDeadline      *ConfigItem[time.Duration]
	RetryPeriod        *ConfigItem[time.Duration]
}
type ConfigBuilder struct {
	labels             labels.Set
	cleanupLease       bool
	leaderElectTimeout time.Duration
	leaseDuration      time.Duration
	renewDeadline      time.Duration
	retryPeriod        time.Duration
}

func (s *ConfigBuilder) Labels(v labels.Set) *ConfigBuilder {
	s.labels = v
	return s
}
func (s *ConfigBuilder) CleanupLease(v bool) *ConfigBuilder {
	s.cleanupLease = v
	return s
}
func (s *ConfigBuilder) LeaderElectTimeout(v time.Duration) *ConfigBuilder {
	s.leaderElectTimeout = v
	return s
}
func (s *ConfigBuilder) LeaseDuration(v time.Duration) *ConfigBuilder {
	s.leaseDuration = v
	return s
}
func (s *ConfigBuilder) RenewDeadline(v time.Duration) *ConfigBuilder {
	s.renewDeadline = v
	return s
}
func (s *ConfigBuilder) RetryPeriod(v time.Duration) *ConfigBuilder {
	s.retryPeriod = v
	return s
}
func (s *ConfigBuilder) Build() *Config {
	return &Config{
		Labels:             NewConfigItem(s.labels),
		CleanupLease:       NewConfigItem(s.cleanupLease),
		LeaderElectTimeout: NewConfigItem(s.leaderElectTimeout),
		LeaseDuration:      NewConfigItem(s.leaseDuration),
		RenewDeadline:      NewConfigItem(s.renewDeadline),
		RetryPeriod:        NewConfigItem(s.retryPeriod),
	}
}

func NewConfigBuilder() *ConfigBuilder { return &ConfigBuilder{} }
func (s *Config) Apply(opt ...ConfigOption) {
	for _, x := range opt {
		x(s)
	}
}

type ConfigOption func(*Config)

func WithLabels(v labels.Set) ConfigOption {
	return func(c *Config) {
		c.Labels.Set(v)
	}
}
func WithCleanupLease(v bool) ConfigOption {
	return func(c *Config) {
		c.CleanupLease.Set(v)
	}
}
func WithLeaderElectTimeout(v time.Duration) ConfigOption {
	return func(c *Config) {
		c.LeaderElectTimeout.Set(v)
	}
}
func WithLeaseDuration(v time.Duration) ConfigOption {
	return func(c *Config) {
		c.LeaseDuration.Set(v)
	}
}
func WithRenewDeadline(v time.Duration) ConfigOption {
	return func(c *Config) {
		c.RenewDeadline.Set(v)
	}
}
func WithRetryPeriod(v time.Duration) ConfigOption {
	return func(c *Config) {
		c.RetryPeriod.Set(v)
	}
}
