name: Env Setup
description: Set environment variables
runs:
  using: "composite"
  steps:
    - name: Import environment variables
      shell: bash
      run: |
        cat <<EOS >> "$GITHUB_ENV"
        KIND_NODE_IMAGE=kindest/node:v1.35.1
        EOS
